"""empty message

Revision ID: 177931080c65
Revises: 81ec6db1deb6
Create Date: 2024-08-02 16:12:02.096458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177931080c65'
down_revision: Union[str, None] = '81ec6db1deb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_role', sa.UUID(), nullable=True))
    op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['id_role'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_fkey', 'users', 'roles', ['role'], ['id'])
    op.drop_column('users', 'id_role')
    # ### end Alembic commands ###
