"""empty message

Revision ID: 81ec6db1deb6
Revises: b6c033ca2449
Create Date: 2024-08-02 15:55:58.712718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ec6db1deb6'
down_revision: Union[str, None] = 'b6c033ca2449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('role', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.drop_table('roles')
    # ### end Alembic commands ###
