"""empty message

Revision ID: cd5540a75906
Revises: 177931080c65
Create Date: 2024-08-02 16:34:38.020603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5540a75906'
down_revision: Union[str, None] = '177931080c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=10), server_default='user', nullable=False))
    op.drop_constraint('users_id_role_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'id_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_role', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_id_role_fkey', 'users', 'roles', ['id_role'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
