version: '3.9'

services:
  fyk_postgres:
    image: postgres:13.8-bullseye
    container_name: ${PROJECT_TITLE}_db
    restart: always
    env_file:
      - .env.deploy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - fyk:/var/lib/postgresql/data
    ports:
      - 12432:5432

volumes:
  fyk:
    name: fyk_postgres