version: '3.9'

services:
  auth_app:
    container_name: ${PROJECT_TITLE}_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.deploy
    ports:
      - 8000:8000
    networks:
      - net

  auth_postgres:
    image: postgres:13.8-bullseye
    container_name: ${PROJECT_TITLE}_db
    restart: always
    env_file:
      - .env.deploy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - auth:/var/lib/postgresql/data
    ports:
      - 5000:5432
    networks:
      - net

volumes:
  auth:
    name: auth_postgres

networks:
  net:
    external: true